# Site settings
title: Ian Tipton
email: itipdev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Open source projects by Ian Tipton
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://itip.github.io" # the base hostname & protocol for your site
twitter_username: iantipton
github_username:  itip

# Build settings
markdown: kramdown
